### ISSUE TITLE
The Movie Of The Week not translated

### ISSUE THREAD

**Issue by henriquev16** [Stremio/stremio-translations#116]
![capturar](https://cloud.githubusercontent.com/assets/4320695/12366843/ab5e3dae-bbd5-11e5-961b-eb6bd17c179f.PNG)

Another missing string? Please check ;)

**Comment by Ivshti** [comment]
Hm..that one will be difficult since the message is generated on the server. I'll think about it. Maybe add "The movie of the week" as a span and allow it to be translated

**Comment by m0k1** [comment]
Or meybe call server with lang flag ? www.server.host/api/or-whatever/movieofweek/:lang ? And impelement language file into server ?

**Comment by Ivshti** [comment]
The thing is, this was (1) fixed: https://github.com/Stremio/stremio-translations/blob/master/en-US.json#L300-L307

and (2) no longer displayed that way in the board

so I think it must be closed
