### ISSUE TITLE
How to added Chinese Language (Interface/UI)

### ISSUE THREAD

**Issue by TristanTW** [Stremio/stremio-translations#135]
How to add my language (Traditional Chinese)~ please help!!

![sds](https://cloud.githubusercontent.com/assets/9483817/13002150/3a24f500-d1a7-11e5-9c00-58ff0de8c6cd.PNG)

**Comment by Ivshti** [comment]
You can add by forking and then creating a new file with the appropriate name - zh-CN.json 

Copy the contents from en file or another one you understand and start translating

Good luck !
