### ISSUE TITLE
Anyone interested in translating the FAQs?

### ISSUE THREAD

**Issue by Ivshti** [Stremio/stremio-translations#161]
Hello guys,

It's the time we need new translations again :) 

Is anyone interested to do translations for our FAQ page?
http://www.strem.io/faq

And again - forgive me for tagging you directly.
French: @Nath74k, @greg0ire
PT-BR: @loopbackbr, @luanhssa

Best,
Ivo from Stremio :)

**Comment by luanhssa** [comment]
i'm on it!

**Comment by henriquev16** [comment]
Count on me!
@liqen and @iRetan will certainly help me :+1:

**Comment by liqen** [comment]
Yes!!! I'm in! :)

**Comment by skanin** [comment]
Iv'e translated the strings to Norwegian Bokmål (nb-NO), what's next? :)

**Comment by cosmoscalibur** [comment]
I am translating spanish version
