### ISSUE TITLE
Croatian Translation

### ISSUE THREAD

**Issue by m0k1** [Stremio/stremio-translations#162]
I see that @boljsa is on the Translation list but i don't see hr file.
So my question is @boljsa can you upload Croatian translation or it's just a blank ?

**Comment by m0k1** [comment]
@Ivshti Update README.md and remove @boljsa  from translator''s  there is no croatian translation ...

Revert https://github.com/Stremio/stremio-translations/pull/159

**Comment by Ivshti** [comment]
@m0k1 ok, reverting
