### ISSUE TITLE
Transifex ?

### ISSUE THREAD

**Issue by m0k1** [Stremio/stremio-translations#169]
Are you planning to integrate transifex ?

**Comment by Ivshti** [comment]
Hm..did not know that existed

Do you know any alternatives? It just looks from first point of view that transifex is too "self-sustained", as in - I don't know if it will be easy to integrate it with the JSON files we use atm. I hope I'm wrong :)

maybe we can research the possible helper tools in that field and pick the best option for us

**Comment by seahindeniz** [comment]
Hey @Ivshti, I suggest Crowdin and Lokalise. They both support open source projects, and they give full access for free

**Comment by jaruba** [comment]
@seahindeniz I can try to find some time next week to research those platforms and see if they are a viable solution for us.

`stremio-translations` is currently used in many projects by us, the ease of using GH and NPM might be hard to replace, but I also see the benefit of a dedicated platform for translations, so we will have to see..

**Comment by seahindeniz** [comment]
Sure @jaruba, thanks for taking into interest.
Furthermore, preparing a GitHub interacting between a translation platform and creating a GitHub action for auto-testing and exchanging the latest changes between sites/projects, might also solve some future issues for you.
_BTW excuse me if this is too bold_
