### ISSUE TITLE
Streaming to LG Smart TV

### ISSUE THREAD

**Issue by advicente** [Stremio/stremio-translations#202]
Hi, 

Not sure if I should report this issue here or to Strem.io directly.
I'm facing problems while streaming any strem.io content to my LG smart TV, when subtitles are in Portuguese (pt-PT). I think the problem is with the latin characters.

Maybe I can upload a photo or if more info is needed please let me know.
Thanks,

**Comment by Ivshti** [comment]
This issue should go to stremio-bugs repository and I don't think that it's something stremio can influence much
stremio sends the subtitles to the TV in an utf-8 encoding, which is pretty universal
Maybe sending in a latin encoding would solve the issue, we'll look into it
