### ISSUE TITLE
How to test the translation?

### ISSUE THREAD

**Issue by Nath74k** [Stremio/stremio-translations#25]
Hello,

I don't understand how to test my translation. How and where to load the .json file?

**Comment by Ivshti** [comment]
Check "how to test in app" here https://github.com/Stremio/stremio-translations

**Comment by Nath74k** [comment]
Yeah I've read that but still I don't understand the "--translation=PATH_TO_JSON" thing

**Comment by Ivshti** [comment]
Open cmd, then type:

%LOCALAPPDATA&\Programs\LNV\Stremio\stremio.exe . --translation=

Then drag & drop the .json file of the translation into the cmd window and press enter

**Comment by Rubenoo** [comment]
In Stremio 4.4.10 I can't test my translations using the: 
%LOCALAPPDATA&\Programs\LNV\Stremio\stremio.exe . --translation=
command in cmd. I just get the default translation and not my own. Is this because this method is outdated?
