### ISSUE TITLE
Brazilian Translation for Website

### ISSUE THREAD

**Issue by jaruba** [Stremio/stremio-translations#335]
There will be some text changes on the site which will leave it largely without brazilian translations. And we would very much like it if we could release these changes along with new translations.

Pinging known brazilian translators: @loopbackbr , @luanhssa , @leonardosnt , @John-Luke , @kelvins , @davidsonsns , @fabianosantosnet , @andrerafaiel 

If anyone has the time and wishes to help, these are the new texts that would require translations:
- https://github.com/Stremio/stremio-translations/pull/333/files#diff-2392fe8c50982e16161a8541ab10d7c0R633-R634
- https://github.com/Stremio/stremio-translations/pull/333/files#diff-2392fe8c50982e16161a8541ab10d7c0R639-R642
- https://github.com/Stremio/stremio-translations/pull/333/files#diff-2392fe8c50982e16161a8541ab10d7c0R814-R862
- https://github.com/Stremio/stremio-translations/pull/333/files#diff-2392fe8c50982e16161a8541ab10d7c0R795-R796
- https://github.com/Stremio/stremio-translations/pull/333/files#diff-2392fe8c50982e16161a8541ab10d7c0R699-R702

The changes would need to be made to the `./pt-BR.json` file.

Thank you all for being Stremio supporters.

**Comment by davidsonsns** [comment]
Great! I can do that. Could you assign it to me?

**Comment by davidsonsns** [comment]
@fabianosantosnet made it here https://github.com/Stremio/stremio-translations/pull/337

**Comment by jaruba** [comment]
Thanks for the help :)
