### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by Holsted777** [Stremio/stremio-translations#34]
Is it possible to translate the text from the right click menu? And also the wrong subtitles menu? 

![ss1](https://cloud.githubusercontent.com/assets/16078997/11500868/2de5b546-9830-11e5-88db-7c7a085c6ea9.png)
![ss2](https://cloud.githubusercontent.com/assets/16078997/11500869/2f3a46b4-9830-11e5-8be8-bb021afb8642.png)

**Comment by Ivshti** [comment]
Sure, I'll get around to adding those translation strings.

there are also a few more context menus that need translation and "new video" / "new episode" in the board

**Comment by Holsted777** [comment]
Sounds good. Also the Resume series.
![ss3](https://cloud.githubusercontent.com/assets/16078997/11501041/6a26f3a2-9831-11e5-901f-ecb1f8e64a26.png)

**Comment by Holsted777** [comment]
And Search field under youtube channels.
![ss4](https://cloud.githubusercontent.com/assets/16078997/11501167/659d1130-9832-11e5-9140-260f2068a3b4.png)

**Comment by Holsted777** [comment]
And this :)

![ss5](https://cloud.githubusercontent.com/assets/16078997/11501284/41c9f100-9833-11e5-883d-474cf0c9d5d6.png)

**Comment by Ivshti** [comment]
Putting up a list:

1. Subtitles - Custom subtitles label
2. Context menus - Library, Player
3. Resume Series
4. Board: new video/new movie/new episode
5. search videos 
6. Intro: "Please create an account"

Any more?

**Comment by Holsted777** [comment]
That's all I have found for now :)

**Comment by Ivshti** [comment]
btw beta for 3.4.1 with all the translations is out: 
http://www.strem.io/Stremio3.4.1.exe for windows
http://www.strem.io/Stremio3.4.1.dmg for mac

next version would add all those missing strings

**Comment by Holsted777** [comment]
Beta looks good and functional.

But the language menu have some small errors that annoys me a liite as some are with upper case and some are with lower case. Would look better if all are with upper case.
French is listed as fr-FR instead of french. 
The two norwegian languages is not next to each other.

**Comment by Ivshti** [comment]
@Holsted777 we're releasing the version with the fixed translation strings tomorrow

**Comment by Holsted777** [comment]
Sounds good :)
