### ISSUE TITLE
Could you add 'hacktoberfest' to the topic of this repository ?

### ISSUE THREAD

**Issue by penguinFSS** [Stremio/stremio-translations#363]
"hacktoberfest" topic to their repository.

I'd like to translate this app and also earn some PR for hacktoberfest. If it's not a problem I'd like to ask you if u can mark this repo and "hacktoberfest" under the about section.

![image](https://user-images.githubusercontent.com/56109794/95018998-33788f00-0663-11eb-8671-4eb5ccb439d2.png)

U see my contribuition was now counted 
![image](https://user-images.githubusercontent.com/56109794/95018948-e5638b80-0662-11eb-95e1-92739a794105.png)

**Comment by Ivshti** [comment]
Done!
