### ISSUE TITLE
I cannot test my translation

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-translations#393]
I cannot test my translation, in Stremio4.4, “%LOCALAPPDATA%\Programs\LNV\Stremio\Stremio.exe. --Translation=PATH_TO_JSON”
This command is invalid.

**Comment by shanyan-wcx** [comment]
Can anyone answer my question?

**Comment by Ivshti** [comment]
Currently there is no way to test translations - sorry for that. With stremio-web it's possible by running the repo locally: https://github.com/stremio/stremio-web, but not with the desktop app
