### ISSUE TITLE
Chinese Translation

### ISSUE THREAD

**Issue by shanyan-wcx** [Stremio/stremio-translations#400]
I have added Chinese translation for some time. When can you add it to the application? In addition, when I open the video introduction page, sometimes the video introduction will be displayed in Chinese, but when I go back and open it again, it will become English. Can I make it display Chinese all the time?

https://user-images.githubusercontent.com/58252651/115744673-67de3f00-a358-11eb-9b52-edbd73a775e9.mp4

**Comment by Ivshti** [comment]
Hello,
We'll include the translation in one of the next releases
