### ISSUE TITLE
Video options popup-size

### ISSUE THREAD

**Issue by xeanhort** [Stremio/stremio-translations#459]
There's a problem in the popup where you can download stream info. The Catalan translation (and probably other languages too) is slightly longer than the English version, so the phrase is cut and doesn't look good (image attached). This issue should be reported in the main repo (make the width of the popup dynamic to fit the texts) but I'm not sure which one is.

Thank you

![image](https://user-images.githubusercontent.com/6896906/144744785-d34b3a54-c40b-40f4-a5e4-d4d5e7f690b7.png)

**Comment by jaruba** [comment]
Hi, we know of this issue and it will be fixed in the next release.
