### ISSUE TITLE
Test missing strings in translation

### ISSUE THREAD

**Issue by Holsted777** [Stremio/stremio-translations#52]
Is it not possible to test the new added stings in program? They dont seem to load?

**Comment by Ivshti** [comment]
Yeah, because the ones I added will be released with today's build

**Comment by Holsted777** [comment]
Yeah thats what I thought.

**Comment by Ivshti** [comment]
@Holsted777 if you want to test : http://www.strem.io/Stremio3.4.4.exe (or .dmg for Mac, .tar.gz for Linux)

**Comment by Holsted777** [comment]
Seems to work fine :)

Only thing i noticed in the new version is a small problem with the wrong subtitles menu.
It always say that subtitle #1 is active even if thats not true. And always state that you can change subtitle to #1 even tho it changes to #2, #3 etc. Same  problem on Danish and English.
![screen shot 2015-12-16 at 19 07 44](https://cloud.githubusercontent.com/assets/16078997/11849681/5a312e3c-a429-11e5-9503-9e0eaa261553.png)

And  the mouse-over menu for the 'report at problem icon' is in english and can't seem to find a translating string for that one.
![screen shot 2015-12-16 at 19 09 15](https://cloud.githubusercontent.com/assets/16078997/11849704/74cb4476-a429-11e5-955d-5259c1d6762b.png)

And if i'm really nitpicking at missing translatable strings here are some more. But I suspect the 'No catching' and 'Connected* string will be troublesome due to layout.

![screen shot 2015-12-16 at 19 18 19](https://cloud.githubusercontent.com/assets/16078997/11849863/5b7fb938-a42a-11e5-9389-fc6a605d9df0.png)

Bet would be nice if it was possible to translate add-ons description.

**Comment by Ivshti** [comment]
Cool, thanks for finding those!

They were hardcoded in the js code and that's why I didn't ifnd them

As for the add-ons, I think it should be part of the add-on manifest:
https://github.com/Ivshti/guidebox-stremio/blob/master/guidebox.js#L13-L24
E..g description_en-US or description_pt-BR

**Comment by Holsted777** [comment]
No problem. Just trying to help :)

Found one more missing string.
![screen shot 2015-12-17 at 10 36 09](https://cloud.githubusercontent.com/assets/16078997/11866300/6878b36c-a4aa-11e5-93e8-d6e1163aaa60.png)

**Comment by Holsted777** [comment]
And some more small things.
![screen shot 2015-12-17 at 10 43 13](https://cloud.githubusercontent.com/assets/16078997/11866440/748c688c-a4ab-11e5-97df-4afb94690c0d.png)
![screen shot 2015-12-17 at 10 43 16](https://cloud.githubusercontent.com/assets/16078997/11866443/76426e38-a4ab-11e5-84ce-d56f15c14dc5.png)
![screen shot 2015-12-17 at 10 45 01](https://cloud.githubusercontent.com/assets/16078997/11866446/790afda6-a4ab-11e5-8455-de78ab96a074.png)

**Comment by Ivshti** [comment]
I covered the "Resume ..." strings in the latest build ( http://dl.strem.io/Stremio%203.4.4.exe ) but as for the titles and On/Off - I'll get around to this with one of the next releases

**Comment by Holsted777** [comment]
Ahh yes I see the string now. Must have missed it. I will translate it.

Great work by the way,

**Comment by Holsted777** [comment]
There seems to be a problem with loading the string "CTX_WATCH_MOBILE"

![screen shot 2015-12-21 at 14 12 58](https://cloud.githubusercontent.com/assets/16078997/11931433/307ab38e-a7ed-11e5-8220-19ee8a770fee.png)

**Comment by Ivshti** [comment]
True, I'll fix this one for the next release @Holsted777
