### ISSUE TITLE
Portuguese translation (Android)

### ISSUE THREAD

**Issue by SalvadorD18** [Stremio/stremio-translations#538]
The Android app has only one Portuguese option from the languages list to choose, as "português", being this one Brazilian Portuguese. Since Stremio has both Portuguese (Portugal) and Portuguese (Brazil), why there's only one option to choose (Brazilian Portuguese) to the Android app? Can you fix this?
![Screenshot_20220805-120130_Stremio](https://user-images.githubusercontent.com/82028566/183064466-ecfe41d1-1d0d-46db-bac5-831e24ec9ea5.jpg)

**Comment by jaruba** [comment]
It looks like a bug, i can see all variations in the Desktop app:
<img width="579" alt="Screenshot 2022-08-05 at 18 11 12" src="https://user-images.githubusercontent.com/1777923/183107080-8305c7c1-4c61-403c-8895-4aa3562a1232.png">

**Comment by SalvadorD18** [comment]
Yes, I know, I have both on my desktop too, but in the Android app is with that bug since other versions to the current. Can you take a look at that, please?

**Comment by jaruba** [comment]
We will definitely look into it

**Comment by SalvadorD18** [comment]
> We will definitely look into it

Thank you!!

**Comment by jaruba** [comment]
@SalvadorD18 this was added in the latest android mobile version: https://blog.stremio.com/stremio-tech-update-19-trakt-scrobbling-and-vlc-on-android-tv/

**Comment by SalvadorD18** [comment]
Perfect, thank you! 🙌
