### ISSUE TITLE
Separate strings from line 1002 — "My" [pt-PT]

### ISSUE THREAD

**Issue by SalvadorD18** [Stremio/stremio-translations#551]
I translated the string of the line 1002 from the pt-PT as "Os meus / As minhas" because the correct translation in the case of the movies is "Os meus filmes" and in the case of the series is "As minhas séries" due to the fact that the "movies" word is masculine and the "series" word is feminine in the Portuguese language. I found where this string is located, as you can see in the image attached, so I want to ask if is possible to separate the string, one for the movies and another to the series in a way for it to be more accurate in the Portuguese translation and probably in other languages that have the same issue.

**Comment by SalvadorD18** [comment]
As it seems that the image wasn't uploaded by the option of the message, here's the image: https://we.tl/t-9brKjtiqJ1

**Comment by SalvadorD18** [comment]
I think that other languages, especially derived from the Latin, like Italian or French, could have the same issue, so it wouldn't be only because of the Portuguese language.

**Comment by jaruba** [comment]
Having "My" as a separate translation word might have been a bad idea to begin with. It might be best to only have translations that include "My", but not have it as a separate word, as various languages will have different issues with this.

@TheBeastLT Thoughts?

**Comment by bhabermann** [comment]
I'm also a portuguese speaker and noticed the same issue as @SalvadorD18 stated.
But I believe the @jaruba solution is better then having "My" concatenated with other words / phrases.

Like in "WEBSITE_MY_ACCOUNT", "My Library", "ADDON_MY"

**Comment by jaruba** [comment]
"My" was removed with this PR: https://github.com/Stremio/stremio-translations/pull/585
