### ISSUE TITLE
Translation Spanish WRONG

### ISSUE THREAD

**Issue by ggomez0** [Stremio/stremio-translations#663]
https://github.com/Stremio/stremio-translations/blob/9c91862cdf8f1f0fb54df870807cd6af18679a89/es-ES.json#L1167

The term "Watched" translates to "VISTO" in Spanish.

"VIENDO" corresponds to "Watching," and the tag is used for indicating the episodes you are currently watching.

**Comment by sbezavvs** [comment]
This string is fixed on proposed PR #678

https://github.com/Stremio/stremio-translations/pull/678
