### ISSUE TITLE
Some TV and YouTube menu Strings not being translated

### ISSUE THREAD

**Issue by henriquev16** [Stremio/stremio-translations#76]
Hi.
I was testing some translations and find this:
![menu](https://cloud.githubusercontent.com/assets/4320695/12053952/0e8847ca-af16-11e5-8e64-bd3eaf4593f5.PNG)

![meuyoutube](https://cloud.githubusercontent.com/assets/4320695/12053983/6b558e54-af16-11e5-9013-8eaa1ed5cc93.PNG)

Some Strings are missing for translation and others simply do not show in the app.

Also:
[See](https://github.com/henriquev16/stremio-translations/commit/718d80140cf5ac8abfd12e7d57c29db9d4b53901)

**Comment by Ivshti** [comment]
That's very interesting, as I cannot find a pattern to why this happens and why not.

I see on the bottom that the one with & symbol doesn't translate, but "Top YouTube collections" also doesn't. All of these are automatically rendered, so the translate is equally applied to all.

Could be a bug in ng-translate

**Comment by henriquev16** [comment]
Thank you! Let me know if you find the bug.
Best regards!
